<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Библиотека-Numpy" data-toc-modified-id="Библиотека-Numpy-0.1"><span class="toc-item-num">0.1&nbsp;&nbsp;</span>Библиотека Numpy</a></span></li><li><span><a href="#Одномерные-массивы" data-toc-modified-id="Одномерные-массивы-0.2"><span class="toc-item-num">0.2&nbsp;&nbsp;</span>Одномерные массивы</a></span><ul class="toc-item"><li><span><a href="#Создание-массива" data-toc-modified-id="Создание-массива-0.2.1"><span class="toc-item-num">0.2.1&nbsp;&nbsp;</span>Создание массива</a></span></li><li><span><a href="#Типы-данных-в-массивах-np.array" data-toc-modified-id="Типы-данных-в-массивах-np.array-0.2.2"><span class="toc-item-num">0.2.2&nbsp;&nbsp;</span>Типы данных в массивах np.array</a></span></li><li><span><a href="#Изменение-массивов-np.array" data-toc-modified-id="Изменение-массивов-np.array-0.2.3"><span class="toc-item-num">0.2.3&nbsp;&nbsp;</span>Изменение массивов np.array</a></span></li></ul></li><li><span><a href="#Многомерные-массивы" data-toc-modified-id="Многомерные-массивы-0.3"><span class="toc-item-num">0.3&nbsp;&nbsp;</span>Многомерные массивы</a></span><ul class="toc-item"><li><span><a href="#Информация-о-массиве" data-toc-modified-id="Информация-о-массиве-0.3.1"><span class="toc-item-num">0.3.1&nbsp;&nbsp;</span>Информация о массиве</a></span></li></ul></li><li><span><a href="#Операции-над-одномерными-массивами" data-toc-modified-id="Операции-над-одномерными-массивами-0.4"><span class="toc-item-num">0.4&nbsp;&nbsp;</span>Операции над одномерными массивами</a></span><ul class="toc-item"><li><span><a href="#Арифметические-операции" data-toc-modified-id="Арифметические-операции-0.4.1"><span class="toc-item-num">0.4.1&nbsp;&nbsp;</span>Арифметические операции</a></span></li></ul></li><li><span><a href="#2-мерные-массивы" data-toc-modified-id="2-мерные-массивы-0.5"><span class="toc-item-num">0.5&nbsp;&nbsp;</span>2-мерные массивы</a></span></li><li><span><a href="#Многомерные-массивы" data-toc-modified-id="Многомерные-массивы-0.6"><span class="toc-item-num">0.6&nbsp;&nbsp;</span>Многомерные массивы</a></span></li><li><span><a href="#Линейная-алгебра" data-toc-modified-id="Линейная-алгебра-0.7"><span class="toc-item-num">0.7&nbsp;&nbsp;</span>Линейная алгебра</a></span></li></ul></li><li><span><a href="#Интегрирование" data-toc-modified-id="Интегрирование-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Интегрирование</a></span><ul class="toc-item"><li><span><a href="#Сохранение-в-файл-и-чтение-из-файла" data-toc-modified-id="Сохранение-в-файл-и-чтение-из-файла-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Сохранение в файл и чтение из файла</a></span></li></ul></li></ul></div>

## Библиотека Numpy

---

Python -- довольно простой, понятный язык программирования, а основоной плюс использования python+jupyter -- написание кода в отдельных ячейках и последовательный запуск кода в ячейках.

Но есть и обратная сторона медали -- Python очень медленный язык. В эпоху big data, при работе с огромными массивами данных даже небольшое отставание языка программирования по скорости становится заметно и критично. Есть, конечно, языки программирования, которые работают намного быстрее (например, С++), но они гораздо сложнее в написании и не интерпретируемы, а компилируемы (то есть, в jupyter notebook'е с такими языками работать бы не получилось). 

Как же найти компромисс? Ответ прост: написать python-библиотеку для работы с массивами данных, функции которой будут написаны на очень быстром языке С++, но которую можно было бы использовать из Python. Эта библиотека называется **NumPy** (НамПай).

Пакет `numpy` предоставляет интерфейс для работы с $n$-мерными массивами. В `numpy` реализовано множество всевозможных операций над массивами в целом. Если задачу можно решить, произведя некоторую последовательность операций над массивами, то с помощью numpy в python это будет столь же эффективно, как в `C` или `matlab`.

Конечно, тот факт, что код numpy написан на С++, накладывает некоторые ограничения на массивы этой библиотеки: в любом numpy-массиве могут храниться элементы только одного типа: например, все float или все string

Этот ноутбук полностью посвещен знакомству с библиотекой numpy и работе с ней

## Одномерные массивы

### Создание массива 

In [1]:
# принято, что numpy импортируют именно так
import numpy as np

Как же завести массив в numpy?

Очень просто! Надо всего лишь перевести обычный python list в np.array:

In [2]:
# 'перевести' python list в np.array -- это обернуть массив в np.array()
a = np.array([3, 4, 1])
print(a)
type(a)

[3 4 1]


numpy.ndarray

Обычный питоновский `print` печатает массивы в удобной форме (точно так же, как и list питона)

In [3]:
print(a)

[3 4 1]


### Типы данных в массивах np.array

Поговорим о типах данных, хранящихся в массивах:

Чаще всего мы будем работать с числовыми массивами, поэтому поговорим о них.

В отличие от чистого питона, в `numpy` есть несколько типов для целых чисел (`int16`, `int32`, `int64`) и чисел с плавающей точкой (`float32`, `float64`). Они отличаются тем, с какой точностью в памяти хранятся элементы массива. 

Чтобы посмотреть, какой тип у вашего массива, можно вывести его dtype:

In [4]:
a.dtype

dtype('int32')

Конечно, можно скастовать массив из одного типа в другой. 

Давайте переведем наш массив 'a' из типа np.int64 в тип np.float32:

In [5]:
a = a.astype(np.float32)
a.dtype

dtype('float32')

Далее мы будем рассматривать n-мерные массивы, для них преобразование типов работает также. И для них все еще все элементы должны иметь одинаковый тип.

### Изменение массивов np.array

Как и list в питоне, массивы np.array - изменяемые объекты. Механика изменений значений в них такая же, как у питоновских list'ов. Давайте в этом убедимся:

In [6]:
a = np.array([3, 4 ,1])

a[1] = 3
print(a)

[3 3 1]


Единственный (но логичный) нюанс: при изменении значения в массиве с элементами одного типа на элемент другого типа новый элемент будет приведен к типу массива:

In [7]:
# или: a = np.array([3, 4 ,1], dtype=np.int64)
a = np.array([3, 4 ,1]).astype(np.int64)

# значение 3.5 будет приведено к типу int64, т.е. станет 3
a[1] = 3.5
print(a)

[3 3 1]


In [8]:
# обратите внимание -- если создается np.array с числами разных типов (int и float), 
# то все числа будут приведены к более точному типу, т.е. float
# таким образом, 1 из целого числа станет числом с плавающей точкой 1.
a = np.array([3., 4. ,1])

# значение 5 будет приведено к типу int64, т.е. станет 5.
a[1] = 5
print(a)

[3. 5. 1.]


А вот добавить к массиву новый элемент в конец чуть сложнее, чем у list. Напомним, в list это делалось с помощью метода .append(). В numpy это также делается с помощью append, но чуть по-другому:

Обратите внимание, что в numpy при append *создается новый массив*, а не происходит добавление элемента в уже существующий массив. Поэтому не рекомендуется создавать массивы с помощью append в numpy.

In [9]:
a = np.array([3, 4 ,1])
# вот так пишется append
b = np.append(a, 6)
print(a,b)

[3 4 1] [3 4 1 6]


## Многомерные массивы

Мы узнали, как создавать и изменять одномерные массивы, как они выглядят в numpy и нюансы приведения типов. Настало время познакомиться с многомерными массивами.

Многомерный массив -- это массив, элементы которого тоже массивы. В принципе, ничего нового, все как и у list в питоне. 

In [10]:
two_dim_array = np.array([[2, 3], [4, 5]])

print(two_dim_array)

[[2 3]
 [4 5]]


In [11]:
three_dim_array = np.array([[[2, 3], [4, 5]], [[5, 6], [7, 8]]])

print(three_dim_array)

[[[2 3]
  [4 5]]

 [[5 6]
  [7 8]]]


Напомним, что в numpy, неважно, в одномерном или многомерном массиве, *все* элементы имеют одинаковый тип

Давайте в этом убедимся:

In [12]:
# 2 и 3 приведутся к типу чисел 4. и 5., т.е. float64
a = np.array([[2, 3], [4., 5.]])
print(a, a.dtype)



[[2. 3.]
 [4. 5.]] float64


### Информация о массиве

Теперь научимся получать основную информацию о массиве

## Операции над одномерными массивами


Далее изучаем файл 01_vectors.ipynb

 ### Арифметические операции

In [13]:
a = np.array([2, 5, 6, 7])
b = np.array([9, 7, 8, 9])

С двумя массивами одинаковой длины

In [14]:
print(a + b)

[11 12 14 16]


In [15]:
print(a - b)

[-7 -2 -2 -2]


In [16]:
print(a * b)

[18 35 48 63]


In [17]:
print(a / b)

[0.22222222 0.71428571 0.75       0.77777778]


In [20]:
print(a ** 2)

[ 4 25 36 49]


`numpy` содержит элементарные функции, которые тоже применяются к массивам поэлементно. Они называются универсальными функциями (`ufunc`).

In [21]:
np.sin, type(np.sin)

(<ufunc 'sin'>, numpy.ufunc)

In [22]:
print(np.sin(a))
print(np.cosh(a))

[ 0.90929743 -0.95892427 -0.2794155   0.6569866 ]
[  3.76219569  74.20994852 201.71563612 548.31703516]


Один из операндов может быть скаляром, а не массивом.

In [23]:
a

array([2, 5, 6, 7])

In [24]:
print(a + 1)

[3 6 7 8]


In [25]:
print(2 * a)

[ 4 10 12 14]


Сравнения дают булевы массивы.

In [26]:
print(a > b)

[False False False False]


In [27]:
print(a < b)

[ True  True  True  True]


In [28]:
print(a == b)

[False False False False]


In [29]:
c = a > 5
print(c)

[False False  True  True]


Кванторы "существует" и "для всех".

In [30]:
np.any(c), np.all(c)

(True, False)

Модификация на месте.

In [31]:
a += 1
print(a)

[3 6 7 8]


In [32]:
b *= 2
print(b)

[18 14 16 18]


In [33]:
b //= 2
print(b)

[9 7 8 9]


При выполнении операций над массивами деление на 0 не вызывает исключения, а даёт значения `np.nan` или `np.inf`.

In [34]:
np.nan + 1, np.inf + 1, np.inf * 0, 1. / np.inf

(nan, inf, nan, 0.0)

Сумма и произведение всех элементов массива; максимальный и минимальный элемент; среднее и среднеквадратичное отклонение.

In [35]:
b.sum(), b.prod(), b.max(), b.min(), b.mean(), b.std()

(33, 4536, 9, 7, 8.25, 0.82915619758885)

In [38]:
x = np.random.normal(size=1000)
x.mean(), x.std()

(-0.009732351054320219, 0.9584170851017623)

Имеются встроенные функции

In [39]:
print(np.sqrt(b))
print(np.exp(b))
print(np.log(b + 1))
print(np.sin(b))
print(np.e, np.pi)

[3.         2.64575131 2.82842712 3.        ]
[8103.08392758 1096.63315843 2980.95798704 8103.08392758]
[2.30258509 2.07944154 2.19722458 2.30258509]
[0.41211849 0.6569866  0.98935825 0.41211849]
2.718281828459045 3.141592653589793


Иногда бывает нужно использовать частичные (кумулятивные) суммы. В нашем курсе такое пригодится.

In [40]:
print(b.cumsum()[::-1])

[33 24 16  9]


Функция `sort` возвращает отсортированную копию, метод `sort` сортирует на месте.

In [41]:
print(np.sort(b))
print(b)

[7 8 9 9]
[9 7 8 9]


In [42]:
b.sort()
print(b)

[7 8 9 9]


Объединение массивов "по-горизонтали" (horizontal stack).

In [43]:
a = np.array([1, 2, 3])
b = np.array([100, 200, 300])

print(np.hstack((a, b)))

[  1   2   3 100 200 300]


Объединение массивов "по-вертикали" (vertical stack).

In [44]:
print(np.vstack((a, b)))

[[  1   2   3]
 [100 200 300]]


Расщепление массива в позициях 3 и 6.

In [45]:
a = np.random.random(10)
np.hsplit(a, [3, 6])

[array([0.16126353, 0.78769287, 0.25447414]),
 array([0.28455226, 0.38802023, 0.4750405 ]),
 array([0.30518962, 0.60432586, 0.66496107, 0.88963813])]

Функции `delete`, `insert` и `append` не меняют массив на месте, а возвращают новый массив, в котором удалены, вставлены в середину или добавлены в конец какие-то элементы.

In [47]:
a = np.arange(10)

In [48]:
a = np.delete(a, [5, 7])
print(a)

[0 1 2 3 4 6 8 9]


In [49]:
a = np.insert(a, 2, [0, 0])
print(a)

[0 1 0 0 2 3 4 6 8 9]


In [50]:
a = np.append(a, [1, 2, 3])
print(a)

[0 1 0 0 2 3 4 6 8 9 1 2 3]


Есть несколько способов индексации массива. Вот обычный индекс.

In [51]:
a = np.linspace(0, 1, 11)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [52]:
b = a[2]
print(b)

0.2


Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.

In [53]:
b = a[2:6]
print(b)

[0.2 0.3 0.4 0.5]


In [54]:
b[0] = -0.2
print(b)

[-0.2  0.3  0.4  0.5]


In [55]:
print(a)

[ 0.   0.1 -0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Диапазон с шагом 2.

In [56]:
b = a[1:10:2]
print(b)

[0.1 0.3 0.5 0.7 0.9]


In [57]:
b[0] = -0.1
print(a)

[ 0.  -0.1 -0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Массив в обратном порядке.

In [58]:
b = a[len(a):0:-1]
print(b)

[ 1.   0.9  0.8  0.7  0.6  0.5  0.4  0.3 -0.2 -0.1]


Подмассиву можно присвоить значение - массив правильного размера или скаляр.

In [59]:
a[1:10:3] = 0
print(a)

[ 0.   0.  -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Тут опять создаётся только новый заголовок, указывающий на те же данные.

In [60]:
b = a[:]
b[1] = 0.1
print(a)

[ 0.   0.1 -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Чтобы скопировать и данные массива, нужно использовать метод `copy`.

In [61]:
b = a.copy()
b[2] = 0
print(b)
print(a)

[0.  0.1 0.  0.3 0.  0.5 0.6 0.  0.8 0.9 1. ]
[ 0.   0.1 -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Можно задать список индексов.

In [62]:
print(a[[2, 3, 5]])

[-0.2  0.3  0.5]


Можно задать булев массив той же величины.

In [63]:
b = a > 0
print(b)

[False  True False  True False  True  True False  True  True  True]


In [64]:
print(a[b])

[0.1 0.3 0.5 0.6 0.8 0.9 1. ]


## 2-мерные массивы

Далее изучаем файл 02_matrices.ipynb

In [65]:
a = np.array([[0.0, 1.0], [-1.0, 0.0]])
print(a)

[[ 0.  1.]
 [-1.  0.]]


In [66]:
a.ndim

2

In [67]:
a.shape

(2, 2)

In [68]:
len(a), a.size

(2, 4)

In [69]:
a[1, 0]

-1.0

Атрибуту `shape` можно присвоить новое значение - кортеж размеров по всем координатам. Получится новый заголовок массива; его данные не изменятся.

In [70]:
b = np.linspace(0, 3, 4)
print(b)

[0. 1. 2. 3.]


In [71]:
b.shape

(4,)

In [72]:
b.shape = 2, 2
print(b)

[[0. 1.]
 [2. 3.]]


Можно растянуть в одномерный массив

In [73]:
print(b.ravel())

[0. 1. 2. 3.]


Арифметические операции поэлементные

In [74]:
a

array([[ 0.,  1.],
       [-1.,  0.]])

In [75]:
b = np.array([[3, 4], 
    [8, 6 ]])
print(b)

[[3 4]
 [8 6]]


In [76]:
print(a + 1)
print(a * 2)
print(a + [0, 1])  # второе слагаемое дополняется до матрицы копированием строк
print(a + np.array([[0, 2]]).T)  # .T - транспонирование
print(a + b)

[[1. 2.]
 [0. 1.]]
[[ 0.  2.]
 [-2.  0.]]
[[ 0.  2.]
 [-1.  1.]]
[[0. 1.]
 [1. 2.]]
[[3. 5.]
 [7. 6.]]


Поэлементное и матричное (только в Python 3.5) умножение.

In [77]:
print(a)

[[ 0.  1.]
 [-1.  0.]]


In [78]:
print(b)

[[3 4]
 [8 6]]


In [79]:
print(a * b)

[[ 0.  4.]
 [-8.  0.]]


In [80]:
print(a @ b)

[[ 8.  6.]
 [-3. -4.]]


In [81]:
print(b @ a)

[[-4.  3.]
 [-6.  8.]]


Умножение матрицы на вектор.

In [82]:
v = np.array([1, -1], dtype=np.float64)
print(b @ v)

[-1.  2.]


In [83]:
print(v @ b)

[-5. -2.]


Если у вас Питон более ранней версии, то для работы с матрицами можно использовать класс `np.matrix`, в котором операция умножения реализуется как матричное умножение.

In [84]:
np.matrix(a) * np.matrix(b)

matrix([[ 8.,  6.],
        [-3., -4.]])

Внешнее произведение $a_{ij}=u_i v_j$

In [85]:
u = np.linspace(1, 2, 2)
v = np.linspace(2, 4, 3)
print(u)
print(v)

[1. 2.]
[2. 3. 4.]


In [86]:
a = np.outer(u, v)
print(a)

[[2. 3. 4.]
 [4. 6. 8.]]


Двумерные массивы, зависящие только от одного индекса: $x_{ij}=u_j$, $y_{ij}=v_i$

In [87]:
x, y = np.meshgrid(u, v)
print(x)
print(y)

[[1. 2.]
 [1. 2.]
 [1. 2.]]
[[2. 2.]
 [3. 3.]
 [4. 4.]]


Единичная матрица.

In [88]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Метод `reshape` делает то же самое, что присваивание атрибуту `shape`.

In [89]:
print(I.reshape(16))

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [90]:
print(I.reshape(8, 2))

[[1. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]]


Строка.

In [91]:
print(I[2])

[0. 0. 1. 0.]


Цикл по строкам.

In [92]:
for row in I:
    print(row)

[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]


Столбец.

In [93]:
print(I[1, 1])

1.0


Подматрица.

In [94]:
print(I[0:2, 1:3])

[[0. 0.]
 [1. 0.]]


Можно построить двумерный массив из функции.

In [95]:
def f(i, j):
    print(i)
    print(j)
    return 10 * i + j

print(np.fromfunction(f, (4, 4), dtype=np.int64))

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


Транспонированная матрица.

In [96]:
print(b.T)

[[3 8]
 [4 6]]


Соединение матриц по горизонтали и по вертикали.

In [97]:
a = np.array([[0, 1], [2, 3]])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.array([[4, 5], [6, 7], [8, 9]])
print(a)
print(b)
print(c)

[[0 1]
 [2 3]]
[[4 5 6]
 [7 8 9]]
[[4 5]
 [6 7]
 [8 9]]


In [98]:
print(np.hstack((a, b)))

[[0 1 4 5 6]
 [2 3 7 8 9]]


In [99]:
print(np.vstack((a, c)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Сумма всех элементов; суммы столбцов; суммы строк.

In [100]:
b

array([[4, 5, 6],
       [7, 8, 9]])

In [101]:
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

39
[11 13 15]
[15 24]


Аналогично работают `prod`, `max`, `min` и т.д.

In [102]:
print(b.max())
print(b.max(axis=0))
print(b.min(axis=1))

9
[7 8 9]
[4 7]


След - сумма диагональных элементов.

In [103]:
np.trace(a)

3

## Многомерные массивы
Необязательный материал

In [104]:
X = np.arange(24).reshape(2, 3, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Суммирование (аналогично остальные операции)

In [105]:
# суммируем только по нулевой оси, то есть для фиксированных j и k суммируем только элементы с индексами (*, j, k)
print(X.sum(axis=0))
# суммируем сразу по двум осям, то есть для фиксированной i суммируем только элементы с индексами (i, *, *)
print(X.sum(axis=(1, 2)))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[ 66 210]


## Линейная алгебра

In [106]:
np.linalg.det(a)

-2.0

Обратная матрица.

In [107]:
a1 = np.linalg.inv(a)
print(a1)

[[-1.5  0.5]
 [ 1.   0. ]]


In [108]:
print(a @ a1)
print(a1 @ a)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


Решение линейной системы $au=v$.

In [109]:
v = np.array([0, 1], dtype=np.float64)
print(a1 @ v)

[0.5 0. ]


In [110]:
u = np.linalg.solve(a, v)
print(u)

[0.5 0. ]


Проверим.

In [111]:
print(a @ u - v)

[0. 0.]


Собственные значения и собственные векторы: $a u_i = \lambda_i u_i$. `l` - одномерный массив собственных значений $\lambda_i$, столбцы матрицы $u$ - собственные векторы $u_i$.

In [112]:
l, u = np.linalg.eig(a)
print(l)

[-0.56155281  3.56155281]


In [113]:
print(u)

[[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


Проверим.

In [114]:
for i in range(2):
    print(a @ u[:, i] - l[i] * u[:, i])

[0.00000000e+00 1.66533454e-16]
[1.11022302e-16 0.00000000e+00]


Функция `diag` от одномерного массива строит диагональную матрицу; от квадратной матрицы - возвращает одномерный массив её диагональных элементов.

In [115]:
L = np.diag(l)
print(L)
print(np.diag(L))

[[-0.56155281  0.        ]
 [ 0.          3.56155281]]
[-0.56155281  3.56155281]


Все уравнения $a u_i = \lambda_i u_i$ можно собрать в одно матричное уравнение $a u = u \Lambda$, где $\Lambda$ - диагональная матрица с собственными значениями $\lambda_i$ на диагонали.

In [116]:
print(a @ u - u @ L)

[[0.00000000e+00 1.11022302e-16]
 [1.66533454e-16 0.00000000e+00]]


Поэтому $u^{-1} a u = \Lambda$.

In [117]:
print(np.linalg.inv(u) @ a @ u)

[[-5.61552813e-01  0.00000000e+00]
 [-4.44089210e-16  3.56155281e+00]]


Найдём теперь левые собственные векторы $v_i a = \lambda_i v_i$ (собственные значения $\lambda_i$ те же самые).

In [118]:
l, v = np.linalg.eig(a.T)
print(l)
print(v)

[-0.56155281  3.56155281]
[[-0.96276969 -0.48963374]
 [ 0.27032301 -0.87192821]]


Собственные векторы нормированы на 1.

In [119]:
print(u.T @ u)
print(v.T @ v)

[[ 1.         -0.23570226]
 [-0.23570226  1.        ]]
[[1.         0.23570226]
 [0.23570226 1.        ]]


Левые и правые собственные векторы, соответствующие разным собственным значениям, ортогональны, потому что $v_i a u_j = \lambda_i v_i u_j = \lambda_j v_i u_j$.

In [120]:
print(v.T @ u)

[[ 9.71825316e-01  0.00000000e+00]
 [-5.55111512e-17  9.71825316e-01]]


# Интегрирование

In [121]:
from scipy.integrate import quad, odeint
from scipy.special import erf

In [122]:
def f(x):
    return np.exp(-x ** 2)

Адаптивное численное интегрирование (может быть до бесконечности). `err` - оценка ошибки.

In [123]:
res, err = quad(f, 0, np.inf)
print(np.sqrt(np.pi) / 2, res, err)

0.8862269254527579 0.8862269254527579 7.101318390472462e-09


erf(x) - функция ошибок Гаусса от аргумента x:

In [124]:
res, err =  quad(f, 0, 1)
print(np.sqrt(np.pi) / 2 * erf(1), res, err)

0.7468241328124269 0.7468241328124271 8.291413475940725e-15


## Сохранение в файл и чтение из файла

In [125]:
x = np.arange(0, 25, 0.5).reshape((5, 10))

# Сохраняем в файл example.txt данные x в формате с двумя точками после запятой и разделителем ';'
np.savetxt('example.txt', x, fmt='%.2f', delimiter=';')

Получится такой файл

In [126]:
d=open("example.txt",'r')

In [127]:
d.read()

'0.00;0.50;1.00;1.50;2.00;2.50;3.00;3.50;4.00;4.50\n5.00;5.50;6.00;6.50;7.00;7.50;8.00;8.50;9.00;9.50\n10.00;10.50;11.00;11.50;12.00;12.50;13.00;13.50;14.00;14.50\n15.00;15.50;16.00;16.50;17.00;17.50;18.00;18.50;19.00;19.50\n20.00;20.50;21.00;21.50;22.00;22.50;23.00;23.50;24.00;24.50\n'

In [128]:
for line in d:
    print(line)

In [129]:
d.close()